### ISSUE TITLE
Homework Feedback

### ISSUE THREAD

**Issue by arun-instructor** [tarisoni/homework_5_responsive_fashion_blog#1]
Tarika,

Nice job on this! Looks really great. Couple of recommendations for you:
- Make sure to put in your meta tag to enable responsiveness on mobile devices.
- Usually with a container you will center the layout to the screen. You can do that by margin-left and margin-right of auto;
- Generally if you're going for a layout that implements a standard document flow you're not really going to need much in the way of absolute/relative positioning. You have this:

``` css
.ad {
    position: relative;
    top: 50%;
    left: 50%;
    transform: translate(-50%);
  }
```

This may complicate your layout further than you need and also make it not respond the way you think it would.
